### PR TITLE
Hotfix/fix-typos

### PR DESCRIPTION
**Pull request by ihoudjedje**
Hi guys,
Wanna contribute so fixed some typos 😆wanna say thanks & congrats for all the work you put into so far on bringing such a great content to the community. Hope to see you soon! Cheers!

### CODE REVIEW

**Review by IOAyman — COMMENTED** [review]
LGTM :+1:

**Comment by IOAyman** [comment]
@ilyeSudo Thanks buddy! Wish to see you soon as well :wink:

**Comment by omartadj** [comment]
Thank you @ilyeSudo

**Comment by ilyeSudo** [comment]
Thanks guys, btw, fixed a typo in the code and made another in a commit 😆

**Comment by ihoudjedje** [comment]
Thanks guys, btw, fixed typos in the code and made one in a commit msg 😭my bad!

**Pull request merged**
